### ISSUE TITLE
Problema con municipios.json

### ISSUE THREAD

**Issue by Brandonage** [pablo-moreno/python-aemet#15]
Hola. 

Lo primero, gracias por compartir este cliente Pablo.

Estoy intentando utilizar la libreria para sacar los datos diarios de meteorologia de aemet.

Al importar el cliente me da el siguiente error porque me falta un fichero llamado municipios.json

```
Traceback (most recent call last):
  File "C:\Users\brandon\AppData\Local\Continuum\anaconda3\envs\py_3.6\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-89da5e43fad4>", line 1, in <module>
    from aforos_inrix.aemet_weather_data import Aemet, Estacion
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\brandon\PycharmProjects\data_import_export\aforos_inrix\aemet_weather_data.py", line 225, in <module>
    class Municipio:
  File "C:\Users\brandon\PycharmProjects\data_import_export\aforos_inrix\aemet_weather_data.py", line 226, in Municipio
    with open(os.path.join(BASE_DIR, 'data', 'municipios.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\brandon\\PycharmProjects\\data_import_export\\aforos_inrix\\data\\municipios.json'
```
¿Que se supone que tiene que ir en este fichero?.

**Comment by pablo-moreno** [comment]
Hola @Brandonage ,

El archivo [municipios.json](https://github.com/pablo-moreno/python-aemet/blob/master/aemet/data/municipios.json) contiene, como su nombre indica, todos los municipios de AEMET. Están incluidos en el paquete para poder consultarlos directamente desde un archivo en vez desde la propia API.

Un saludo.
